name: Github actions second workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install Dependencies
        run:  mvn clean

      - name: Run Tests
        run: mvn test
  sonarqube:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -  name: SonarQube Scan
         uses: sonarsource/sonarqube-scan-action@master

  deploy:
    needs:
      - sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install Dependencies
        run: mvn clean

      - name: Deployment
        run: echo "Deploying..."