name: Github actions second workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: echo "GET CODE"
      - name: Download dependencies
        run: echo "Download dependencies"
